### ISSUE TITLE
最新uui对grid表格中自定义的渲染校验失效。

### ISSUE THREAD

**Issue by zhanghy7** [iuap-design/neoui-grid#10]
### Bug 报告
grid中有用到自定义的渲染类型,然后最新的uui3.1对该字段不进行校验了，但是之前的版本中是可以校验的。

- __Package version(s)__: (版本号) uui3.1

#### 描述这个问题:
![x8 2pd8 avdo cc9zofd4](https://cloud.githubusercontent.com/assets/23067197/21181396/aa777526-c238-11e6-91da-604136a17f01.png)
就是这块，这块这个rendertype的渲染类型换成自定义的类型，平台所提供的校验方法就不对该字段进行校验了。

#### 当前的行为:
grid中有用到自定义的渲染类型,然后最新的uui3.1对该字段不进行校验，直接跳过。

#### 期望的行为:
grid中有用到自定义的渲染类型,在使用平台所提供的校验方法时候也对该字段进行校验。

**Comment by LiuYueKai** [comment]
http://tinper.org/
下载3.1.18版本可以解决此问题
