### ISSUE TITLE
grid中editType使用自定义方法后，平台提供的校验方法无法生效

### ISSUE THREAD

**Issue by SoDanTengAndYou** [iuap-design/neoui-grid#11]
#### 描述这个问题:
在使用自定义编辑事件后，grid控件的提供的校验就无法生效，比如："required":true  必填项
![image](https://cloud.githubusercontent.com/assets/24285229/21249096/af1df5d4-c376-11e6-8836-3d8ca4e17de3.png)

#### 当前的行为:
在使用自定义编辑方法后，grid控件的提供的校验就无法生效，比如："required":true  必填项
#### 期望的行为:
在使用自定义编辑方法后，grid控件的自身提供的校验也能同时生效

**Comment by LiuYueKai** [comment]
@SoDanTengAndYou 最新代码已经修改此问题，另外是否可以提供QQ之类的联系方式，方便问题的快速跟进及解决。
