### ISSUE TITLE
grid控件下拉框不会随着页面的滑动而自动定位

### ISSUE THREAD

**Issue by SoDanTengAndYou** [iuap-design/neoui-grid#12]
#### 描述这个问题:
grid控件下拉框不会随着页面的滑动而自动定位
#### 当前的行为:
选择下拉框，页面未滑动时：
![image](https://cloud.githubusercontent.com/assets/24285229/21309547/b7bc2d00-c619-11e6-8fe5-989cbccbc9cf.png)
页面滑动后：
![image](https://cloud.githubusercontent.com/assets/24285229/21309912/20a38bdc-c61b-11e6-82a5-d464dc42f835.png)
#### 期望的行为:
 下拉框能随页面的滑动而滑动，且能否增加根据用户输入自动补全提示功能。

**Comment by HuYuee** [comment]
请提供你的QQ，我们会有相关的技术人员联系你，并帮你解决问题

**Comment by SoDanTengAndYou** [comment]
@HuyueHappy 我们已经是好友啦~~~

**Comment by HuYuee** [comment]
那你QQ找下我
