### ISSUE TITLE
页面默认初始化浏览态grid中的checkbox控件仍可编辑

### ISSUE THREAD

**Issue by zhaozhaob** [iuap-design/neoui-grid#20]
打开一个页面默认浏览态 grid表格中的checkBox控件仍可编辑
如果某人编辑态进入 然后dataTable.setEnable(false);
手动设置为浏览台则复选框类型控件不可编辑

**Comment by HuYuee** [comment]
这个问题已经解决，在3.2.4版本将更新，敬请期待
