### ISSUE TITLE
u.js更新到版本后，发现switchRender没有根据数据0或1设置为开或关

### ISSUE THREAD

**Issue by glud123** [iuap-design/neoui-grid#21]
### Bug 报告
u.js更新到版本后，发现switchRender没有根据数据0或1设置为开或关。

- __Package version(s)__: (版本号)

#### 描述这个问题:
renderType为switchRender，原规定中使支持0或1的，但是更新到版本后，发现switchRender没有根据数据0或1设置为开或关。

**Comment by HuYuee** [comment]
现在已经支持通过0或1来设置为开或关，3.2.4版本将支持该功能，敬请期待！
