### ISSUE TITLE
grid表格中编辑态数字格式校验问题

### ISSUE THREAD

**Issue by zhaozhaob** [iuap-design/neoui-grid#24]
当数字整数位大于3位时格式化后会出现逗号分隔符  就会提示 数字格式不对  如999,999.00

如果小于3位则不回提示 如 12.3

**Comment by HuYuee** [comment]
现在整数大于3位时，编辑态的时候不会出现逗号分隔符。问题已解决，近期将发布3.2.4版本。下载新版本即可！
