### ISSUE TITLE
grid表格精度根据表格设置问题

### ISSUE THREAD

**Issue by zhaozhaob** [iuap-design/neoui-grid#25]
精度问题：
             表格需要初始化时需要根据请求数据设置每个input框的精度，
             目前iuap没有相应的方法（只能初始化时设置每列的精度，或者在点击input框时设置该输入框的精度）。

**Comment by HuYuee** [comment]
通过setColumnPrecision来动态设置grid列的精度，具体使用方法可以参考文档http://docs.tinper.org/moy/grid-api.html#setColumnPrecision
