### ISSUE TITLE
grid表格获取当前行问题

### ISSUE THREAD

**Issue by zhaozhaob** [iuap-design/neoui-grid#26]
表格勾选获取当前行问题：
            勾选表格第一行，不勾选第二行，点第二行履约义务编码参照，选择参照后会将值带到第一行的履约义务编码中（uiReferComp.js获取行信息错误）。

**Comment by LiuYueKai** [comment]
此问题应该为参照的写法存在问题，未设置行对应关系，请联系参照组件进行相应修改。
