### ISSUE TITLE
grid表格设置了固定高度之后，最下方的横向滚动轴需要滑到最低才能看见

### ISSUE THREAD

**Issue by glud123** [iuap-design/neoui-grid#27]
### Bug 报告
grid表格设置了固定高度之后，最下方的横向滚动轴需要滑到最低才能看见
- __Package version(s)__: (版本号)

#### 描述这个问题:
grid表格设置固定高度之后，随着行数增加右侧出现滚动条，列数增加会出现横向滚动条，但是需要滑动右侧的滚动条到最低，才能看见横向滚动条来进行操作。

#### 期望的行为:
希望设置固定高度之后直接在高度范围下方显示横向滚动条，而不需要将右侧的滚动表条滚到最下才能看到横向滚动条。

**Comment by HuYuee** [comment]
可以通过在grid的u-meta中设置参数height，来设置高度
