### ISSUE TITLE
多选下拉控件问题

### ISSUE THREAD

**Issue by zhaozhaob** [iuap-design/neoui-grid#28]
场景：
下拉中有三个选项  自由：-1  已审核 ：1 未审核 2
如果先选择value=-1的自由 然后在选择 value=1的已审核就选不上  
其他情况都能正常选中 比如先选未审核 再选已审核都没问题 

经测试 只有第一项选value=-1  第二项选value=1的项是 第二项第一次点击是无法选中的 后续再点击就选中向会出现重复的混乱情况

u.js 6182行   var index = (this.value + ',').indexOf(val + ',');  已经选中-1,  在选择1 判断1,则返回已经选中

建议修改为  var index = ( ','+this.value).indexOf(','+val);

**Comment by LiuYueKai** [comment]
已修改，将在下一版本中更新此问题
