### ISSUE TITLE
grid表格中的下拉列表的控件展示与kero的下拉列表控件展示不一致

### ISSUE THREAD

**Issue by glud123** [iuap-design/neoui-grid#29]
### Bug 报告
grid表格中的下拉列表的控件展示与kero的下拉列表控件展示不一致
- __Package version(s)__: (版本号)

#### 描述这个问题:
kero的下拉列表控件右侧会有相关联的只是箭头，grid控件中编辑状态下，下拉列表右侧没有指示箭头，相同功能的样式风格不统一，希望能统一其风格。

**Comment by HuYuee** [comment]
需求已实现，近期将发布3.2.4版本。下载新版本即可！
