### ISSUE TITLE
kero控件中的多选下拉控件选择多个选项后，然后在清除，title没有更新。

### ISSUE THREAD

**Issue by glud123** [iuap-design/neoui-grid#30]
### Bug 报告
kero控件中的多选下拉控件选择多个选项后，然后在清除，title没有更新。
- __Package version(s)__: (版本号)

#### 描述这个问题:
kero控件中的多选下拉控件选择多个选项后，然后在取消选择，但是title中的数据没有更新，鼠标悬停依旧显示之前选择的选项

**Comment by HuYuee** [comment]
问题已解决，近期将发布3.2.4版本。下载新版本即可！
