### ISSUE TITLE
控件值更新问题

### ISSUE THREAD

**Issue by zhaozhaob** [iuap-design/neoui-grid#34]
rowUtilFunObj.eq(oldValue, value)
当value="123"  oldValue="000123"时
会作为浮点类型比较 返回true 导致值更新失败

但是控件是u-text 不能自己主动转换为浮点

**Comment by HuYuee** [comment]
请问是在何场景下？在grid中吗？具体的编辑控件是什么类型的？string？还是integer？还是float？
