### ISSUE TITLE
grid行单击赋值问题

### ISSUE THREAD

**Issue by zhaozhaob** [iuap-design/neoui-grid#35]
卡片表体grid表格两行或以上数据 注册编辑前事件 A字段可编辑 其他字段不可编辑

第一行A字段 原值100  第二行A字段原值 200

将第一行A字段单击进入编辑态后修改为150 

然后单击第二行其他非编辑字段 第一行变成浏览态

然后点击第一行非编辑字段 这时会将第二行A字段的200 赋值给第一行的A字段

导致第一行的A字段由150变为200

**Comment by HuYuee** [comment]
请详细描述或判断下具体是什么问题。我没法复现该问题，这样我没法定位问题原因。

**Comment by HuYuee** [comment]
也希望你能按照issue模板来填写，这样我也能快速定位问题。非常感谢！
