### ISSUE TITLE
grid列标题水平对齐方式参数

### ISSUE THREAD

**Issue by s330526719** [iuap-design/neoui-grid#36]
问题描述:

增加grid列参数，用来控制列标题的水平对齐方式（居中、居右）

**Comment by HuYuee** [comment]
表头： .u-grid-header-link 表体： .u-grid-content-td-div;或者在每一列通过设置"textAlign":"right"，默认是left

**Comment by s330526719** [comment]
样式是全局修改，我只需要修改某些grid。已经尝试过textAlign，但他只能修改数据的水平对齐方式并不影响列标题，我最终需要的效果是： 列标题局中、数据居右，能不能考虑扩展一个新的参数专门用于控制列标题水平对齐方式

**Comment by HuYuee** [comment]
改样式不一定是全局修改，你可以在grid上面定义一个id，然后写样式的时候通过#id去动态的匹配到你想要的那个grid，然后自己定义样式就行了
