### ISSUE TITLE
gird控件保留小数位数有时候会失效

### ISSUE THREAD

**Issue by SoDanTengAndYou** [iuap-design/neoui-grid#7]
<div options='{"field":"realStockAmount","dataType":"String","title":"实际用于质押的股权金额（元）","editType":"float","editable":false,"editOptions":{"validType":"float","precision":"2"}}'></div>
在grid定义的时候，在editOptions中已经定义保留了两位小数。可是在显示的时候会出现类似：387.5581395348837的情况。

**Comment by whizbz11** [comment]
field为float手动输入会自动保留2位小数
