### ISSUE TITLE
grid触发valueChange事件，出现了报错

### ISSUE THREAD

**Issue by SoDanTengAndYou** [iuap-design/neoui-grid#8]
在失去焦点的时候出现报错：Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
 编辑了单元格后通过点击别的行来触发valuechange事件，会触发点击行的valuechange事件，而不是编辑行的valuechange事件

**Comment by whizbz11** [comment]
根据event.rowId获取当前行再取值即可。viewModel.entityAgreementDt.getRowByRowId(event.rowId).getValue("transferType")
